### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by smarek** [derlaft/synco#1]
Hey, this might be interesting solution you've got here, but there is no documentation on how to use it.
Could you please, for starters, put up some idea on how to build and run Synco ?
Thank you a lot!

**Comment by derlaft** [comment]
Hi, @smarek 

Thank you for being interested in this shitty project :) It has some issues, but still works pretty fine.

I've added some documentation to the readme file.

Feel free to ask any questions.

By the way, I have never tried to run this on Windows, but there should not be any serious issues that will prevent you to do that.

**Comment by smarek** [comment]
You're great @derlaft, this docs should suffice greatly.
I'm assessing multiple mpv-sync-over-network solutions, so I'll get back to you with more details along the way.
No Windows required :)

**Comment by derlaft** [comment]
Hmm. Can you please give links for that solutions? The main reason I wrote this is that I found nothing.

**Comment by derlaft** [comment]
Oh. Found https://github.com/mpv-player/mpv/issues/1272. OK.
