### ISSUE TITLE
Playback speed is not synchronized

### ISSUE THREAD

**Issue by L-as** [derlaft/synco#3]
Changing the playback speed doesn't affect other viewers, and instead causes the video to pause after a short while seemingly.

**Comment by derlaft** [comment]
Should be quite simple to implement :)

> and instead causes the video to pause after a short while seemingly.

Yeah, that's a pereodic check that makes sure that all the clients are synced.

**Comment by derlaft** [comment]
Fixed by 05fdb43

![image](https://user-images.githubusercontent.com/852606/98422781-f43bc480-208c-11eb-8b15-4d54080698fd.png)
